apiVersion: apps/v1
kind: Deployment
metadata:
  name: uygygyggyddddcd-webserver
  namespace: uygygyggyddddcd
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uygygyggyddddcd-secret
              key: rootpassword
        image: gcr.io/pc-api-6479467557629758909-343/uygygyggyddddcd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: uygygyggyddddcd-pvc-sym-m
          mountPath: /var/www/upload/image
      volumes:
      - name: uygygyggyddddcd-pvc-sym-m
        persistentVolumeClaim:
          claimName: uygygyggyddddcd-pvc-sym-uploud
---
apiVersion: v1
kind: Service
metadata:
  name: uygygyggyddddcd-web-service
  namespace: uygygyggyddddcd
  labels:
    run: uygygyggyddddcd-web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
---
apiVersion: v1                  
kind: PersistentVolumeClaim     
metadata:                       
   name: uygygyggyddddcd-pvc-sym-uploud
   namespace: uygygyggyddddcd
spec:                           
   accessModes:                  
   - ReadWriteOnce              
   resources:                   
      requests:                 
         storage: 1Gi   
